#!/usr/bin/zsh

alias zshconfig='vim ~/zsh/.zshrc'
alias zshreload='source ~/zsh/.zshrc'
alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
# alias vim='nvim'
alias nv='nvim'
alias nf='neofetch'
alias pf='pfetch'
alias ff='fastfetch'
alias unimatrix='unimatrix -s 92'
alias cmatrix='unimatrix'
