general.import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 10.75

[window]
decorations = "Full"
padding = { x = 8, y = 6 }
dimensions = { columns = 99, lines = 28 }
